Repository KOSA-2nd-Team3/front-end, pull requests merged in 2025-06, with the labels that each got.

#3 feat: 구독상세페이지 관리 및 파티 참가
  src/views/DashboardDetailView.vue
  src/views/DashboardView.vue
  src/views/PlatformListView.vue
Labels: enhancement

#6 feat: 읽지 않은 메시지 카운트 및 채팅 멤버 리스트 추가
  src/views/ChatView.vue
Labels: enhancement

#8 feat: 파티인원이 다 차면 모든 사람들에게 이메일전송
  src/views/DashboardView.vue
  src/views/PlatformListView.vue
Labels: enhancement

#13 feat: dashboard
  src/views/DashboardView.vue
Labels: enhancement

#12 feat: 무한 스크롤 및 정렬 기능 추가
  src/views/DashboardDetailView.vue
  src/views/MainView.vue
  src/views/PlatformListView.vue
Labels: enhancement

#15 feat: 그룹채팅 참여 버튼 클릭 시 해당 파티 채팅방 이동 및 이미지 로드 추가
  src/router/index.js
  src/views/ChatView.vue
  src/views/DashboardDetailView.vue
Labels: feat

#20 feat: 파티원이 구독 파티 가입 시 채팅방에 채팅 참여인원 추가 및 구독 상세 페이지로 이동
  src/views/PlatformListView.vue
Labels: feat

#23 fix: 소셜 로그인 요청 처리
  src/views/LoginView.vue
Labels: fix

#26 feat: 프로필 페이지 추가
  src/components/AppHeader.vue
  src/views/ProfileView.vue
Labels: feat

#30 feat: 구인글 만료, 구인글 시작
  src/views/DashboardDetailView.vue
  src/views/DashboardView.vue
  src/views/PlatformListView.vue
Labels: feat, fix

#33 fix: 불필요한 버튼 삭제 및 플랫폼뷰에서 가입하기 넘기기
  src/views/PlatformListView.vue
Labels: fix

#38 feat: 파티 삭제 및 탈퇴 시 채팅 방 삭제 및 탈퇴 코드 추가
  src/views/DashboardDetailView.vue
Labels: feat

#46 feat: 플랫폼 이름 옆에 id 추가
  src/views/DashboardView.vue
Labels: feat

#48 fix: 맨 아래 채팅방 푸터에 짤리는 것 수정
  src/views/ChatView.vue
Labels: fix
