Repository KOSA-2nd-Team3/front-end, pull requests merged in 2025-07, with the labels that each got.

#54 fix: api-endpoint 변경
  src/views/DashboardDetailView.vue
  src/views/DashboardView.vue
  src/views/MainView.vue
  src/views/PlatformListView.vue
  src/views/SubscriptionCreateView.vue
  src/views/SubscriptionSelectionView.vue
Labels: fix

#56 feat: 닉네임 수정
  src/views/ProfileView.vue
Labels: feat

#62 fix: 채팅방 제목 서비스네임 -> 서비스명으로 수정
  src/views/ChatView.vue
Labels: fix

#64 refactor: 불필요한 코드 제거, message 위치 변경
  src/main.js
  src/views/DashboardDetailView.vue
  src/views/PlatformListView.vue
Labels: refactor

#65 fix: Local dev수정한 것 dev에 머지
  src/views/ChatView.vue
  src/views/DashboardDetailView.vue
  src/views/PlatformListView.vue
  src/views/ProfileView.vue
  src/views/SubscriptionCreateView.vue
Labels: fix
